#!/bin/perl -w

use strict;
use DBI;

my $dbh = DBI->connect(
    "DBI:mysql:database=eyeImageTest;host=127.0.0.1",
    "eye", "life", {'RaiseError'=>1});
my @urls = `find -name *.png`;
print @urls;

foreach my $url (@urls) {
    $dbh->do("INSERT INTO imageURL(URL) VALUES('$url')");
}
$dbh->disconnect();
